ROCIC-22: Generate dir for each jpeg image converted from BIFF
huynguyen-zuhlke/roche-image-converter pull request #5
Opened 2024-09-11 06:54 UTC by huynguyen-zuhlke

2024-09-12 04:15 UTC, davidlee-zuhlke requested changes

2024-09-12 09:07 UTC, davidlee-zuhlke commented on src/conversion/file_writer.py
> +            continue
We will create a tech-debt ticket for this.

2024-09-13 02:40 UTC, huynguyen-zuhlke commented on src/conversion/bif_to_jpeg.py
> +        output_jpeg_file_dir = prepare_output_dir(input_path, tiff_output_dir)
done. Thanks Lee

2024-09-13 02:40 UTC, huynguyen-zuhlke commented on src/conversion/bif_to_jpeg.py
>  def bif_to_jpeg(input_path, tiff_output_dir):
done. Thanks Lee

2024-09-13 02:40 UTC, huynguyen-zuhlke commented on src/conversion/bif_to_jpeg.py
> +            f"Conversion complete: {filename} in {end - start} seconds. Output image location at {output_jpeg_file_dir}")
changed. Thanks Lee

2024-09-13 02:40 UTC, huynguyen-zuhlke commented on src/conversion/file_writer.py
> +def jpeg_write(file: TiffFile, output_jpeg_file_dir: str):
changed. Thanks Lee

2024-09-13 02:40 UTC, huynguyen-zuhlke commented on src/conversion/file_writer.py
> +            continue
This will be a tech debt and will be implemented on another ticket.

2024-09-13 02:41 UTC, huynguyen-zuhlke commented on src/utils.py
> +
done. Thanks Lee

2024-09-13 03:15 UTC, merged