ROCIC-25: Init logging
huynguyen-zuhlke/roche-image-converter pull request #6
Opened 2024-09-16 08:51 UTC by huynguyen-zuhlke

2024-09-17 03:19 UTC, davidlee-zuhlke requested changes

2024-09-17 03:19 UTC, davidlee-zuhlke commented on src/logger.py
> +        raise ValueError("An error occurred during the conversion.")
It might make more sense to handle exceptions when configuring the logger, but not when actually logging things. Also it's more helpful letting the exception surface than raise a `ValueError` saying "An error occurred during the conversion."

2024-09-18 03:06 UTC, davidlee-zuhlke approved these changes
Good stuff
Only one quick change needed. Please go ahead and merge the branch when it's done. Thanks!

2024-09-18 03:06 UTC, davidlee-zuhlke commented on src/conversion/bif_to_tiled_tiff.py
> +        logger.info(
Can we move `start = time.time()` to the top of the function.

2024-09-18 05:50 UTC, huynguyen-zuhlke commented on src/conversion/bif_to_tiled_tiff.py
> +        logger.info(
resolved

2024-09-18 05:51 UTC, merged